version: '3'

services:
  # Configuções para o MySQL
  db-nutrido-alimento:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.db
    image: mysql:8.0
    container_name: mysql-nutrido-alimento
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_PASSWORD=root
      # - MYSQL_DATA_BASE=nutrido_alimento_db
      # - MYSQL_USER=root
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
      # - mysql.nutrido-alimento:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - nutrido_network

  # Client Web para acessar o MYSQL
  sgbd-adminer:
    image: adminer
    container_name: db-adminer
    ports:
      - 8085:8080
    networks:
      - nutrido_network

networks:
  nutrido_network:
    driver: bridge

# volumes:
#   mysql.nutrido-alimento:
